name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run RSpec tests
        run: |
          cd test
          bundle exec rspec -fd *_spec.rb
      - name: "Tar files"
        if: ${{ success() || failure() }}
        run: tar -cvf rspec-tests-${{ matrix.ruby-version }}.tar test/reports
      - uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: rspec-tests-${{ matrix.ruby-version }}
          path: rspec-tests-${{ matrix.ruby-version }}.tar
          retention-days: 14
